import dayjs from 'dayjs';
import { VendorType } from 'app/shared/model/enumerations/vendor-type.model';
import { VendorCategory } from 'app/shared/model/enumerations/vendor-category.model';
import { OfficeFunctionality } from 'app/shared/model/enumerations/office-functionality.model';
import { Country } from 'app/shared/model/enumerations/country.model';

export interface IVendor {
  id?: number;
  vendorNameEnglish?: string;
  vendorNameArabic?: string | null;
  vendorId?: string;
  vendorAccountNumber?: string | null;
  vendorCRNumber?: string | null;
  vendorVATNumber?: string | null;
  vendorType?: keyof typeof VendorType | null;
  vendorCategory?: keyof typeof VendorCategory | null;
  vendorEstablishmentDate?: string | null;
  vendorLogoContentType?: string | null;
  vendorLogo?: string | null;
  height?: number | null;
  width?: number | null;
  taken?: string | null;
  uploaded?: string | null;
  contactFullName?: string | null;
  contactEmailAddress?: string;
  contactPrimaryPhoneNo?: string | null;
  contactPrimaryFaxNo?: string | null;
  contactSecondaryPhoneNo?: string | null;
  contactSecondaryFaxNo?: string | null;
  officeLocation?: string | null;
  officeFunctionality?: keyof typeof OfficeFunctionality | null;
  websiteURL?: string | null;
  buildingNo?: string | null;
  vendorStreetName?: string | null;
  zipCode?: string | null;
  districtName?: string | null;
  additionalNo?: string | null;
  cityName?: string | null;
  unitNo?: string | null;
  country?: keyof typeof Country | null;
  googleMap?: string | null;
  combinedAddress?: string | null;
  cRCertificateUploadContentType?: string | null;
  cRCertificateUpload?: string | null;
  vATCertificateUploadContentType?: string | null;
  vATCertificateUpload?: string | null;
  nationalAddressUploadContentType?: string | null;
  nationalAddressUpload?: string | null;
  companyProfileUploadContentType?: string | null;
  companyProfileUpload?: string | null;
  otherUploadContentType?: string | null;
  otherUpload?: string | null;
  cash?: string | null;
  credit?: string | null;
  letterOfCredit?: string | null;
  others?: string | null;
}

export const defaultValue: Readonly<IVendor> = {};
